project:
  type: website
  output-dir: docs

website:
  title: "nature"
  
  page-footer:
      border: true
  
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ki5n2/nature
        
format:
  html:
    theme: cosmo
    css: styles.css
    
editor: visual

