project:
  type: website

website:
  title: "nature"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ki5n2/nature
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

