project:
  type: website
  output-dir: docs

website:
  title: "nature"
  
  page-footer:
      border: true
  
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ki5n2/nature

  sidebar:
    style: "docked"
    search: true
    contents: auto
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: true

editor: visual

